// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofile.proto

package protofiles

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{0}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransactionResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Step                 int32    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{1}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransactionResponse) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *TransactionResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "protofiles.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "protofiles.TransactionResponse")
}

func init() { proto.RegisterFile("protofile.proto", fileDescriptor_b28b201cc727c47d) }

var fileDescriptor_b28b201cc727c47d = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x4d, 0xd4, 0x42, 0x47, 0xb0, 0x32, 0x82, 0x14, 0x17, 0x5a, 0xba, 0xea, 0xaa, 0x88,
	0xfe, 0x83, 0xbb, 0x82, 0x84, 0xe2, 0x3e, 0xd6, 0x11, 0xaa, 0x36, 0x13, 0x33, 0xe9, 0xc2, 0xbf,
	0x97, 0xc6, 0xa2, 0x7d, 0x3c, 0xde, 0xee, 0xce, 0xc9, 0x70, 0x26, 0x17, 0x0a, 0x1f, 0x38, 0xf2,
	0xdb, 0xf8, 0x49, 0x6d, 0x4a, 0x08, 0x7f, 0x40, 0xea, 0x27, 0xc0, 0x3e, 0x58, 0x27, 0x76, 0x88,
	0x23, 0x3b, 0x43, 0x5f, 0x33, 0x49, 0x44, 0x84, 0x93, 0xc7, 0xc0, 0x53, 0xa9, 0x2a, 0xd5, 0xe4,
	0x26, 0x65, 0x3c, 0x07, 0xdd, 0x73, 0xa9, 0x13, 0xd1, 0x3d, 0xe3, 0x15, 0x64, 0x76, 0xe2, 0xd9,
	0xc5, 0xf2, 0xb8, 0x52, 0x8d, 0x36, 0xeb, 0x54, 0x0f, 0x70, 0xb9, 0x63, 0x14, 0xcf, 0x4e, 0x68,
	0x59, 0x97, 0x68, 0xe3, 0x2c, 0xab, 0x74, 0x9d, 0x96, 0x53, 0x12, 0xc9, 0x27, 0xf1, 0xa9, 0x49,
	0x19, 0x2b, 0x38, 0x7b, 0x25, 0x19, 0xc2, 0xe8, 0x17, 0x45, 0xf2, 0xe7, 0x66, 0x8b, 0xee, 0xdf,
	0xe1, 0xa2, 0x63, 0x47, 0xdf, 0x9b, 0x4b, 0xf8, 0x0c, 0x45, 0x67, 0x3f, 0x68, 0x8b, 0x6e, 0xda,
	0xff, 0xaa, 0xed, 0x7e, 0xcf, 0xeb, 0xdb, 0x83, 0xef, 0xbf, 0xbf, 0xae, 0x8f, 0xee, 0xd4, 0x4b,
	0x96, 0x76, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0x24, 0x89, 0xb8, 0x48, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MoneyTransactionClient is the client API for MoneyTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoneyTransactionClient interface {
	MakeTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (MoneyTransaction_MakeTransactionClient, error)
}

type moneyTransactionClient struct {
	cc *grpc.ClientConn
}

func NewMoneyTransactionClient(cc *grpc.ClientConn) MoneyTransactionClient {
	return &moneyTransactionClient{cc}
}

func (c *moneyTransactionClient) MakeTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (MoneyTransaction_MakeTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MoneyTransaction_serviceDesc.Streams[0], "/protofiles.MoneyTransaction/MakeTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &moneyTransactionMakeTransactionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MoneyTransaction_MakeTransactionClient interface {
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type moneyTransactionMakeTransactionClient struct {
	grpc.ClientStream
}

func (x *moneyTransactionMakeTransactionClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MoneyTransactionServer is the server API for MoneyTransaction service.
type MoneyTransactionServer interface {
	MakeTransaction(*TransactionRequest, MoneyTransaction_MakeTransactionServer) error
}

// UnimplementedMoneyTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedMoneyTransactionServer struct {
}

func (*UnimplementedMoneyTransactionServer) MakeTransaction(req *TransactionRequest, srv MoneyTransaction_MakeTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method MakeTransaction not implemented")
}

func RegisterMoneyTransactionServer(s *grpc.Server, srv MoneyTransactionServer) {
	s.RegisterService(&_MoneyTransaction_serviceDesc, srv)
}

func _MoneyTransaction_MakeTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MoneyTransactionServer).MakeTransaction(m, &moneyTransactionMakeTransactionServer{stream})
}

type MoneyTransaction_MakeTransactionServer interface {
	Send(*TransactionResponse) error
	grpc.ServerStream
}

type moneyTransactionMakeTransactionServer struct {
	grpc.ServerStream
}

func (x *moneyTransactionMakeTransactionServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MoneyTransaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.MoneyTransaction",
	HandlerType: (*MoneyTransactionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MakeTransaction",
			Handler:       _MoneyTransaction_MakeTransaction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protofile.proto",
}
